apiVersion: apps/v1
kind: Deployment
metadata:
  name: bt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bt-app
  template:
    metadata:
      labels:
        app: bt-app
    spec:
      containers:
      - image: pch18/baota:clear
        name: bt-app

---

apiVersion: v1
kind: Service
metadata:
  name: bt-app
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "http-port-tcp"
    port: 8888
  selector:
    app: bt-app
