apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode-app4 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vscode-app4
  template:
    metadata:
      labels:
        app: vscode-app4
    spec:
      containers:
      - image: vscwjm/myvscode:v1
        name: vscode-app4
---
apiVersion: v1
kind: Service
metadata:
  name: vscode-app4
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "http-port-tcp"
    port: 8080
  selector:
    app: vscode-app4
